# Generated by Django 4.1.7 on 2023-03-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('S', 'Шестигранник'), ('R', 'Круг')], default='R', max_length=1)),
                ('diameter', models.CharField(max_length=255)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('value3', models.FloatField(blank=True, null=True)),
                ('time_measure', models.DateField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('con', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='charts2.consumer')),
                ('gr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='charts2.grade', verbose_name='Марка стали')),
                ('kd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='charts2.kind')),
            ],
        ),
    ]
